### ISSUE TITLE
Typo in userinfo.io example

### ISSUE THREAD

**Issue by sebz** [vdurmont/userinfo-js#3]
Hi Vincent, 

Your example says:
> [..] insert the following code between the `<head>` and `</head>` tags of your page:
> `<script type="text/javascript" href="//cdnjs.cloudflare.com/ajax/libs/userinfo/1.0.0/userinfo.min.js"></script>` 

Using a `href` instead of a `src` attribute. Nice try, you almost got me :wink:

Cheers!

**Comment by vdurmont** [comment]
Wow you're totally right, that's a dumb mistake!
I fixed it!
