### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by sebz** [vdurmont/userinfo-js#4]
Hi,

I get a security error while trying to access http://api.userinfo.io/userinfos from an HTTPS page.
It could be nice to have an https version.

Thanks.

**Comment by vdurmont** [comment]
Yeah you're right, I've been meaning to do that for a while.
I'll try to set it up soon.

**Comment by sebz** [comment]
Great, thanks!

**Comment by vdurmont** [comment]
Hey,

I just release a new version with https: version 1.1.0.
It will soon be available on cdnjs but you can already download it in the [release](https://github.com/vdurmont/userinfo-js/releases/tag/v1.1.0)

Enjoy ;)

**Comment by sebz** [comment]
:+1: Thanks man!
