### ISSUE TITLE
Are you open for mantaining data?!

### ISSUE THREAD

**Issue by dotku** [vdurmont/userinfo-js#7]
There is only English data return, I would like add some foreign languages, such as Chinese.

**Comment by vdurmont** [comment]
Hi!
I think it would be pretty hard to implement. As I said on the website, I merge several public databases to get the location. Those databases don't provide anything else than English.

One of the solutions could be to call a translation service but it would greatly slow the response and it would make me rely on other services. I'm not a big fan of this idea.

Thanks for the suggestion but it won't be one of my priorities for now.

If you need the data in Chinese, maybe you could take the response userinfo sends and try to resolve it on a translation service (e.g. https://cloud.google.com/translate/docs).

**Comment by dotku** [comment]
@vdurmont Yes, I have tried Google Translate, it doesn't translate well on some locations. It not really focusing on GEO domain. I might create a opensource project, but if there is exiting one, it would be better.
