### ISSUE TITLE
Uncaught ReferenceError: UserInfo is not defined

### ISSUE THREAD

**Issue by michaeljarizala** [vdurmont/userinfo-js#9]
Hi Vincent!

Michael here. I have been wanting to integrate the API on our Shopify store's checkout page. FYI, the custom js codes that we can put on the checkout page is limited to 8000 chars only by Shopify for some reason. Also, Shopify's checkout page is served on a different server outside of our full control, so any files we upload on our domain won't matter on the checkout page.

This limitation forces us to become more creative on how we insert our custom js codes notwithstanding the character limit. Due to this, there is only one way we know we can integrate the API (at least for now). However, we are getting an uncaught referenceerror and couldn't integrate it properly. I am wondering if you can give some advice?

![screenshot_2](https://user-images.githubusercontent.com/23579045/39923142-0100635c-5555-11e8-9d79-ddbfbbee06d1.png)

Thanks a lot!

Best,

Michael

**Comment by igorbenic** [comment]
The error happens because you're calling `getUI()` right away even if the UserInfo JS has not yet been loaded from Cloudflare.

Something like this might help. Found on https://stackoverflow.com/questions/14644558/call-javascript-function-after-script-is-loaded

````
function getUI() { 
 // your code here... 
}
var uiLib = document.createElement("script");
uiLib.type = "text/javascript";
uiLib.src = "your_src_here";
if(uiLib.readyState) {  //IE
    uiLib.onreadystatechange = function() {
      if ( uiLib.readyState === "loaded" || uiLib.readyState === "complete" ) {
        uiLib.onreadystatechange = null;
        getUI();
      }
    };
  } else {  //Others
    uiLib.onload = function() {
      getUI();
    };
  }
document.head.appendChild(uiLib);
````

**Comment by michaeljarizala** [comment]
Hi @igorbenic 

I didn't think of that lol I was literally checking the actual external <script></script> if it has been loaded then run the function, like so `var apiLoaded = $('script[src="<external JS>"]').length;` which I believe was wrong lmao. Anyway, your solution works really great and we can now integrate the API just right. 

Thanks a lot! Cheers!
